//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDCInput
    {
        public int BCDInputSeq { get; set; }
        public string Program { get; set; }
        public string Dynpro { get; set; }
        public string ID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> ScreenInput { get; set; }
        public string TransactionCode { get; set; }
        public string ValueFieldName { get; set; }
        public Nullable<int> ReportID { get; set; }
    }
}
