//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUserReportFields
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string Plant { get; set; }
        public string Material { get; set; }
        public string MaterialType { get; set; }
        public string Year { get; set; }
        public string LanguageKey { get; set; }
        public string OrderNumber { get; set; }
        public string SalesOrganisation { get; set; }
        public string PurchasingDocumnet { get; set; }
        public string SalesOrder { get; set; }
        public string Delivery { get; set; }
    }
}
