//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public int ID { get; set; }
        public string FromCurrency { get; set; }
        public string ExchangeRateType { get; set; }
        public string ToCurrency { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public double ExchangeRate { get; set; }
    }
}
