//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSheetOptions
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public string ReportSheet { get; set; }
        public bool MaterialPrice { get; set; }
        public bool ProductHierarchy { get; set; }
        public bool CustomerHierarchy { get; set; }
        public bool SalesValue { get; set; }
        public bool QuantityUnit { get; set; }
        public bool Currency { get; set; }
        public bool CurrencyYear { get; set; }
        public bool CreateNewPlan { get; set; }
        public bool SavePriorities { get; set; }
        public bool BudgetVersion { get; set; }
        public bool FormatGraph { get; set; }
        public bool SaveGroup { get; set; }
        public bool SaveBinTest { get; set; }
        public bool SaveExcludedTypes { get; set; }
        public bool UpdateSAP { get; set; }
        public bool ShowOptions { get; set; }
        public bool ShelfLifeTypes { get; set; }
        public bool MaterialsIncluded { get; set; }
        public bool SaveList { get; set; }
        public bool SaveManko { get; set; }
        public bool ShowStocks { get; set; }
        public bool ShowMD04Data { get; set; }
    }
}
