//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSelections
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public string FieldName { get; set; }
        public string ScreenID { get; set; }
        public string SelectionOption { get; set; }
        public string ControlType { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Mandatory { get; set; }
        public bool MultipleSelection { get; set; }
        public string Sign { get; set; }
        public string LowValue { get; set; }
        public string HighValue { get; set; }
        public string DayType { get; set; }
        public string Period { get; set; }
        public int DateLimit { get; set; }
        public bool Required { get; set; }
        public int MaxDateLimit { get; set; }
        public bool Include { get; set; }
        public bool LowValueVisible { get; set; }
        public bool HighValueVisible { get; set; }
        public bool UpdateLowValue { get; set; }
        public bool UpdateHighValue { get; set; }
    }
}
