//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStatistics
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ReportID { get; set; }
        public int ReportCount { get; set; }
        public Nullable<System.DateTime> LastOpened { get; set; }
    }
}
