//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGroups
    {
        public int ID { get; set; }
        public int ReportSubGroupID { get; set; }
        public string ReportSubGroupName { get; set; }
        public int ReportGroup { get; set; }
    }
}
