//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public int ReportGroup { get; set; }
        public byte[] ReportDefinition { get; set; }
        public bool BeginGroup { get; set; }
        public string QueryName { get; set; }
        public bool Week { get; set; }
        public bool Month { get; set; }
        public bool Year { get; set; }
        public bool MultipleSelection { get; set; }
        public bool MaterialHelp { get; set; }
        public bool ReportOptions { get; set; }
        public bool Enabled { get; set; }
    }
}
