//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReportSelections
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public int UserID { get; set; }
        public int VariantID { get; set; }
        public string ScreenID { get; set; }
        public string Kind { get; set; }
        public string Sign { get; set; }
        public string SelectionOption { get; set; }
        public string LowValue { get; set; }
        public string HighValue { get; set; }
        public bool MultipleSelection { get; set; }
    }
}
